# Generated by Django 4.2.1 on 2023-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='view_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
