# Generated by Django 4.2.1 on 2023-08-17 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wall', '0002_alter_userpost_last_edit_alter_userpost_view_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
