# Generated by Django 4.2.1 on 2023-05-17 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='group/logo/%Y/%m/%d/')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
