# Generated by Django 4.2.1 on 2023-08-17 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grouppost_last_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='user_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
