# Generated by Django 4.2.1 on 2023-05-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldata',
            name='town',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
