# Generated by Django 4.2.1 on 2023-05-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_customuser_gender_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
